export enum CRONJOB_NAME {
	DAILY_COURSE_REMINDERS = 'DAILY_COURSE_REMINDERS',
	DAILY_START_COURSE_SCHEDULER = 'DAILY_START_COURSE_SCHEDULER',
	DAILY_QUESTION_SET_ASSIGNMENT = 'DAILY_QUESTION_SET_ASSIGNMENT',
	DAILY_QUESTION_SET_ASSIGNMENT_PARENT = 'DAILY_QUESTION_SET_ASSIGNMENT_PARENT',
	DAILY_PROCESS_YESTERDAY_USER_ANSWERS = 'DAILY_PROCESS_YESTERDAY_USER_ANSWERS',

	DAILY_STUDENT_VIDEO_ASSIGNMENT = 'DAILY_STUDENT_VIDEO_ASSIGNMENT',
	DAILY_LESSON_ASSIGNMENT = 'DAILY_LESSON_ASSIGNMENT',

	CAREGIVER_REMIND_STUDENT_NOTIFICATION = 'CAREGIVER_REMIND_STUDENT_NOTIFICATION',

}
